POST http://localhost/customer
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IkJPT0tJTkdfU1lTVEVNIiwibmFtZSI6IkJvb2tpbmcgQVBJIFN5c3RlbSBVc2VyIiwiZ3JvdXBzIjpbIkJPT0tJTkdfQURNSU4iLCJQUklDSU5HX1VTRVIiLCJPQ0NVUEFOQ1lfQURNSU4iLCJOT1RJRklDQVRJT05fVVNFUiIsIlVTRVJfQURNSU4iLCJBU1NFVF9BRE1JTiIsIlNUQUZGX0FETUlOIiwiUEVSU09OX0FETUlOIiwiQ1VTVE9NRVJfQURNSU4iLCJJTlZPSUNFX0FETUlOIl0sImlhdCI6MTYxNzg3MDYyOX0.9JWbYbVSbFLXrVWEIFL6iIEoVfl3yZ1m47tSQqfNFA4

{
    "name":"German"
}